# Generated by Django 5.0.6 on 2024-07-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="product name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="product description"),
                ),
                (
                    "stripe_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="product stripe id"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="is product active ?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="price description"
                    ),
                ),
                (
                    "stripe_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="price stripe id"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="is price active ?"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
