# Generated by Django 5.0.6 on 2024-07-05 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="clients",
            field=models.ManyToManyField(
                related_name="products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
