# Generated by Django 5.0.6 on 2024-07-05 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_clients"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": (
                    ("access_video", "can read texts and videos"),
                    ("access_text", "can read texts but not videos"),
                )
            },
        ),
    ]
