# Generated by Django 5.0.6 on 2024-07-09 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"permissions": (("access_video", "can read texts and videos"),)},
        ),
    ]
