# Generated by Django 5.0.6 on 2024-07-05 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="is order paid ?"),
                ),
                (
                    "stripe_customer_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="order stripe customer email",
                    ),
                ),
                (
                    "stripe_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="order stripe intent id",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
