# Generated by Django 5.0.6 on 2024-07-05 08:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="order creation date and time",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="order update date and time",
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="item unit price"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=1, verbose_name="item quantity"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="item creation date and time"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="item update date and time"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.order",
                    ),
                ),
            ],
        ),
    ]
