# Generated by Django 5.0.6 on 2024-07-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_order_created_order_updated_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="order creation date and time"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="order update date and time"
            ),
        ),
    ]
