# Generated by Django 5.0.6 on 2024-07-09 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_alter_order_created_alter_order_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
    ]
