# Generated by Django 5.0.6 on 2024-07-09 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_remove_order_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="unit_price",
        ),
    ]
