# Generated by Django 5.0.6 on 2024-07-09 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_orderitem_unit_price"),
        ("products", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.price"
            ),
        ),
    ]
