# Generated by Django 5.0.6 on 2024-06-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="article publication date"
            ),
        ),
    ]
